import { defineConfig } from 'vite'
import path from 'path'

export default defineConfig({
  resolve: {
    alias: { '@': path.resolve(__dirname, 'src') },
  },
  build: {
    outDir: '.vite/build',
    lib: {
      entry: 'electron/main/index.ts',
      formats: ['cjs'],
      fileName: () => 'main.js',
    },
    rollupOptions: {
      external: [
        'electron',
        'better-sqlite3',
        // Node builtins (also covered by builtinModules but listed for clarity)
        'fs',
        'fs/promises',
        'path',
        'crypto',
        'os',
        'child_process',
        'util',
        'stream',
        'stream/web',
        'events',
        'buffer',
        'url',
        'http',
        'https',
        'net',
        'tls',
        'zlib',
        'assert',
        'worker_threads',
        'dns',
        'readline',
        'v8',
        'vm',
        'node:fs',
        'node:fs/promises',
        'node:path',
        'node:os',
        'node:crypto',
        'node:child_process',
        'node:util',
        'node:stream',
        'node:events',
        'node:buffer',
        'node:url',
        'node:http',
        'node:https',
        'node:net',
        'node:tls',
        'node:zlib',
        'node:assert',
        // Heavy CJS deps that do dynamic requires / native bindings — must be
        // resolved from node_modules at runtime instead of bundled.
        'mammoth',
        'pdf-parse',
        'pdfjs-dist',
        // SDKs and other Node-only libs we keep external to avoid CJS interop quirks
        '@anthropic-ai/sdk',
        'openai',
        '@modelcontextprotocol/sdk',
        'gray-matter',
        'glob',
        'drizzle-orm',
        'drizzle-orm/better-sqlite3',
        'drizzle-orm/sqlite-core',
        'electron-updater',
      ],
    },
    emptyOutDir: false,
    minify: false,
  },
})
